### ISSUE TITLE
Don't allow adding the same user more than once in friends dropdown

### ISSUE THREAD

**Issue by cpf5193** [kberg721/Tagalong#25]

**Comment by kberg721** [comment]
maybe we can create an array that matches the indices of the friend array, but it can hold boolean values to determine whether we should display the name or not.

**Comment by kberg721** [comment]
@cpf5193

**Comment by cpf5193** [comment]
Will be done for now using a multi-select dropdown, related to issue #15

**Comment by cpf5193** [comment]
Fixed in #28
