### ISSUE TITLE
Create Event and Invitee tables in respective databases

### ISSUE THREAD

**Issue by kberg721** [kberg721/Tagalong#37]

**Comment by kberg721** [comment]
@cpf5193

**Comment by cpf5193** [comment]
BasicNameValuePair doesn't support integers, so hostEventCount needs to be changed to a varchar. I also changed the name 'address' to 'location' and 'date' to 'time' to be more in line with what they actually represent

**Comment by cpf5193** [comment]
Replaced by issue #44
