### ISSUE TITLE
Update db schemas

### ISSUE THREAD

**Issue by cpf5193** [kberg721/Tagalong#44]
depends on #43 

Update db schemas based on #43. Php files have already been added/updated

**Comment by cpf5193** [comment]
**Event**
hostEmail: VARCHAR(50)
hostEventCount: VARCHAR(11)
name: VARCHAR(200)
location: VARCHAR(2000)
time: VARCHAR(20)
description: VARCHAR(2000)

**Invited**
hostEmail: VARCHAR(50)
hostEventCount: VARCHAR(11)
friendName: VARCHAR(100)
friendEmail: VARCHAR(50)
friendFBId: VARCHAR(25)
isAttending: VARCHAR(1)

**User**
name: VARCHAR(100)
email: VARCHAR(100)
password: VARCHAR(100)
eventCount: VARCHAR(11)

**Comment by kberg721** [comment]
updated my schema
